walk = "git"

[formatter.biome]
command = "biome"
options = ["format", "--write"]
includes = ["*.json"]

[formatter.formatjson5]
command = "formatjson5"
includes = ["*.json5"]
options = ["--replace", "--indent", "2"]

[formatter.ktfmt]
command = "ktfmt"
includes = ["*.kt", "*.kts"]

[formatter.rumdl]
command = "rumdl"
options = ["fmt"]
includes = ["*.md"]

[formatter.tombi]
command = "tombi"
includes = ["*.toml"]
options = ["format"]

[formatter.toml-sort]
command = "toml-sort"
includes = ["*.toml"]
options = ["--in-place"]

[formatter.yamlfmt]
command = "yamlfmt"
includes = ["*.yaml", "*.yml"]
